FROM node:22

WORKDIR /app

# Kopieer package.json en package-lock.json om afhankelijkheden te installeren
COPY package*.json ./

RUN npm install

# Kopieer de rest van de code naar de container
COPY . .

# Exposeer de interne poort (deze is alleen binnen de container bereikbaar)
EXPOSE 3000

# Start de applicatie
CMD ["npm", "start"]
