version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}

  app:
    build: .
    container_name: app
    ports:
      - "3000:3000"
    environment:
      MONGO_URL: mongodb://mongo:27017
      DB_NAME: ${DB_NAME}
    depends_on:
      - mongo
    volumes:
      - .:/app

networks:
  default:
    name: app_network

