version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: membersDB
    volumes:
      - ./data:/data/db  # Persistent storage
    ports:
      - "27017:27017"  # Expose MongoDB only to other services (not the host)

  api:
    build: .
    container_name: api_service
    restart: always
    environment:
      PORT: 3000
      MONGO_URL: mongodb://user:password@mongo:27017/membersDB
    depends_on:
      - mongo
    ports:
      - "3000:3000"  # Expose API to the host
    volumes:
      - .:/app  # Mount code for live development
      - /app/node_modules  # Prevent overwriting node_modules
