name: 'coverage'

on:
  pull_request:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: PaulsBoekenClubMembers/package-lock.json
          
      - name: Install dependencies
        run: npm ci
        working-directory: PaulsBoekenClubMembers

      - name: Run tests with coverage
        run: npm test -- --coverage
        working-directory: PaulsBoekenClubMembers 

      - name: Jest coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          coveragePath: PaulsBoekenClubMembers/coverage/lcov.info