name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: PaulsBoekenClubMembers/package-lock.json

    - name: Install dependencies
      run: npm ci
      working-directory: PaulsBoekenClubMembers

    - name: Build project
      run: npm run build --if-present
      working-directory: PaulsBoekenClubMembers

    - name: Run tests
      run: npm test
      working-directory: PaulsBoekenClubMembers

  coverage:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
      - name: Jest coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:        
          working-directory: PaulsBoekenClubMembers
          coveragePath: PaulsBoekenClubMembers/coverage/lcov.info 